import type { Prisma } from "@prisma/client";
import { prisma } from "./db";

/**
 * Conversation logging — every chat turn lands here so nothing is lost.
 *
 * Design notes:
 *  • Conversation IDs are generated by the client (UUID stored in
 *    localStorage) and passed in with each request. We don't trust them
 *    blindly — `ensureConversation` upserts so a malformed ID just
 *    becomes a new row.
 *  • Message-append is fire-and-forget from the chat route's perspective:
 *    if the DB write fails we log but never block the user-facing stream.
 *  • Token counts come from the AI SDK's `onFinish` callback. Storing
 *    them per-message lets us answer "how much did this conversation
 *    cost?" without re-running the model.
 */

const WA_LINK_RE = /https?:\/\/(wa\.me|api\.whatsapp\.com)\//i;

export function hasWhatsAppLink(text: string): boolean {
  return WA_LINK_RE.test(text);
}

export async function ensureConversation(
  id: string,
  meta: { businessId?: string; userAgent?: string; locale?: string } = {}
) {
  return prisma.conversation.upsert({
    where: { id },
    create: {
      id,
      businessId: meta.businessId,
      userAgent: meta.userAgent,
      locale: meta.locale,
    },
    // Only set businessId on create — never overwrite once a conversation
    // is bound to a business, even if the request later resolves to a
    // different one (shouldn't happen, but defensive).
    update: {},
  });
}

type AppendUserArgs = {
  conversationId: string;
  content: string;
};

export async function appendUserMessage({
  conversationId,
  content,
}: AppendUserArgs) {
  await prisma.$transaction([
    prisma.message.create({
      data: { conversationId, role: "user", content },
    }),
    prisma.conversation.update({
      where: { id: conversationId },
      data: { messageCount: { increment: 1 } },
    }),
  ]);
}

type AppendAssistantArgs = {
  conversationId: string;
  content: string;
  model?: string;
  promptTokens?: number;
  completionTokens?: number;
};

export async function appendAssistantMessage({
  conversationId,
  content,
  model,
  promptTokens,
  completionTokens,
}: AppendAssistantArgs) {
  const handoff = hasWhatsAppLink(content);

  const updates: Prisma.ConversationUpdateInput = {
    messageCount: { increment: 1 },
    ...(handoff ? { whatsappHandoff: true } : {}),
  };

  await prisma.$transaction([
    prisma.message.create({
      data: {
        conversationId,
        role: "assistant",
        content,
        model,
        promptTokens,
        completionTokens,
      },
    }),
    prisma.conversation.update({
      where: { id: conversationId },
      data: updates,
    }),
  ]);
}

type AppendToolArgs = {
  conversationId: string;
  toolName: string;
  toolInput: unknown;
  toolOutput: unknown;
};

export async function appendToolMessage({
  conversationId,
  toolName,
  toolInput,
  toolOutput,
}: AppendToolArgs) {
  await prisma.message.create({
    data: {
      conversationId,
      role: "tool",
      content: `${toolName} called`,
      toolName,
      toolInput: toolInput as Prisma.InputJsonValue,
      toolOutput: toolOutput as Prisma.InputJsonValue,
    },
  });
}

export async function listConversations(limit = 50) {
  return prisma.conversation.findMany({
    orderBy: { updatedAt: "desc" },
    take: limit,
    include: {
      _count: { select: { messages: true, leads: true } },
    },
  });
}

export async function getConversation(id: string) {
  return prisma.conversation.findUnique({
    where: { id },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
      leads: true,
    },
  });
}
